package com.expidev.gcmapp.service;

/**
 * Created by William.Randall on 1/22/2015.
 */
public enum Type
{
    RETRIEVE_ASSOCIATED_MINISTRIES,
    RETRIEVE_ALL_MINISTRIES,
    SAVE_ASSOCIATED_MINISTRIES,
    AUTH,
    TRAINING,
    DOWNLOAD_TRAINING,
    SYNC_TRAINING,
    SYNC_ASSIGNMENTS,
    SYNC_CHURCHES,
    SEARCH_MEASUREMENTS,
    RETRIEVE_MEASUREMENT_DETAILS
}
