package com.expidev.gcmapp.service;

/**
 * Created by William.Randall on 1/22/2015.
 */
public enum Type
{
    RETRIEVE_ALL_MINISTRIES,
    SAVE_ASSOCIATED_MINISTRIES,
    SYNC_TRAINING,
    SYNC_DIRTY_TRAINING,
    SYNC_ASSIGNMENTS,
    SYNC_CHURCHES,
    SYNC_DIRTY_CHURCHES,
    SAVE_MEASUREMENTS,
    SAVE_MEASUREMENT_DETAILS,
    SYNC_MEASUREMENTS
}
