package com.expidev.gcmapp.service;

/**
 * Created by William.Randall on 1/22/2015.
 */
public enum Type
{
    RETRIEVE_ASSOCIATED_MINISTRIES,
    RETRIEVE_ALL_MINISTRIES,
    SAVE_ASSOCIATED_MINISTRIES,
    AUTH,
    TRAINING,
    DOWNLOAD_TRAINING,
    SYNC_ASSIGNMENTS,
    SYNC_CHURCHES,
    SYNC_DIRTY_CHURCHES,
    SAVE_MEASUREMENTS,
    SAVE_MEASUREMENT_DETAILS,
    SYNC_MEASUREMENTS,
    RETRIEVE_AND_SAVE_MEASUREMENTS
}
