package com.expidevapps.android.measurements.model;

public enum Task {
    CREATE_CHURCH, EDIT_CHURCH, ADMIN_CHURCH, VIEW_CHURCH, CREATE_TRAINING, EDIT_TRAINING, VIEW_TRAINING,
    UPDATE_PERSONAL_MEASUREMENTS, UPDATE_MINISTRY_MEASUREMENTS, VIEW_ADMIN_ONLY_MEASUREMENTS
}
